import Head from "next/head";
import Link from "next/link";
import { IoHeart } from "react-icons/io5"; //https://react-icons.github.io/react-icons/icons?name=io5
import { getAllPosts } from "../utils/mdx";
import siteMetadata from "/data/siteMetadata";

export default function BlogList({ posts }) {
  return (
    <>
    <Head>
        <title>博客 - {siteMetadata.title}</title>
        <meta name="author" content={siteMetadata.author} />
        <meta name="description" content={siteMetadata.description} />
        <link rel="icon" href="/favicon.ico" />

        {/* For Soical Meida (OpenGraph) */}
        <meta property="og:image" content="网站宽屏图（16:9）" />
        <meta property="og:image:alt" content="网站宽屏图的描述" />
        <meta name="og:type" content="summary" />
        <meta property="og:title" content={siteMetadata.title} />
        <meta property="og:description" content={siteMetadata.description} />

        {/* For Twitter */}
        <meta name="twitter:site" content="@Pudge_1996" />
        <meta name="twitter:creator" content="@Pudge_1996" />
      </Head>
    <div className="layout">
      <h1>博客</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>mdx-bundler</code>.
      </p>

      <div className="flex flex-col gap-8">
        {posts.map((post, index) => (
          <section className="flex flex-col">
            
            <Link
              key={index}
              href={`/blog/${post.slug}`}
              className="hover:no-underline group ring-default" alt={post.frontmatter.title}
            >
              <p className="text-[22px] font-semibold my-0 group-hover:text-blue-700 group-active:text-blue-900 dark:group-active:text-blue-500 dark:group-hover:text-blue-400 leading-snug">
                {post.frontmatter.title}
              </p>
              <p className="mt-1 mb-0 text-secondary text-base elis-2">
                {post.frontmatter.description}
              </p>
            </Link>
            <div className="flex gap-2 items-center mt-1 text-tertiary"><time className="">{post.frontmatter.date}</time><Link href={post.frontmatter.recommendLink} className="empty:hidden w-fit flex items-center link-color-none force-link-icon ring-default force-link hover:font-medium" target="_blank" rel="noopener noreferrer">{post.frontmatter.recommend}</Link></div> 
          </section>
        ))}
      </div>
    </div>
    </>
  );
}

export const getStaticProps = async () => {
  const posts = getAllPosts();

  return {
    props: { posts },
  };
};
